--
-- PostgreSQL database dump
--

\restrict qe1fm8QQfR2nt0aYEwXMy0DhEqrtaysikfL9tm8Ibeg3RYSvqoVXIyCgcFbOVdP

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caracter_mobi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caracter_mobi (
    id bigint NOT NULL,
    descripcion character varying(550) NOT NULL
);


ALTER TABLE public.caracter_mobi OWNER TO postgres;

--
-- Name: caracter_mobi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.caracter_mobi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caracter_mobi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: concepto_pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.concepto_pago (
    codigo character varying(5) NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.concepto_pago OWNER TO postgres;

--
-- Name: cuenta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuenta (
    id bigint NOT NULL,
    nombre_usuario character varying(100) NOT NULL,
    correo_electronico character varying(254) NOT NULL,
    disposicion boolean NOT NULL,
    estado_cuenta_id character varying(5) NOT NULL,
    firebase_uid character varying(255)
);


ALTER TABLE public.cuenta OWNER TO postgres;

--
-- Name: cuenta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuenta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuenta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: datos_cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.datos_cliente (
    id bigint NOT NULL,
    rfc character varying(13) NOT NULL,
    nombre_fiscal character varying(150) NOT NULL,
    nombre character varying(150) NOT NULL,
    "apellidoPaterno" character varying(150) NOT NULL,
    "apelidoMaterno" character varying(150) NOT NULL,
    telefono character varying(15) NOT NULL,
    correo_electronico character varying(254) NOT NULL,
    dir_colonia character varying(150) NOT NULL,
    dir_calle character varying(150) NOT NULL,
    dir_numero character varying(50) NOT NULL,
    cuenta_id bigint NOT NULL,
    tipo_cliente_id character varying(5) NOT NULL
);


ALTER TABLE public.datos_cliente OWNER TO postgres;

--
-- Name: datos_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.datos_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.datos_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: encuesta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.encuesta (
    id bigint NOT NULL,
    personal integer NOT NULL,
    equipamiento integer NOT NULL,
    servicios integer NOT NULL,
    salon integer NOT NULL,
    mobiliario integer NOT NULL,
    reservacion_id bigint NOT NULL
);


ALTER TABLE public.encuesta OWNER TO postgres;

--
-- Name: encuesta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.encuesta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.encuesta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipamiento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipamiento (
    id bigint NOT NULL,
    nombre character varying(75) NOT NULL,
    descripcion character varying(550) NOT NULL,
    costo numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    tipo_equipa_id bigint NOT NULL
);


ALTER TABLE public.equipamiento OWNER TO postgres;

--
-- Name: equipamiento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipamiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipamiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estado_cuenta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estado_cuenta (
    codigo character varying(5) NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.estado_cuenta OWNER TO postgres;

--
-- Name: estado_equipa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estado_equipa (
    codigo character varying(5) NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.estado_equipa OWNER TO postgres;

--
-- Name: estado_mobil; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estado_mobil (
    codigo character varying(5) NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.estado_mobil OWNER TO postgres;

--
-- Name: estado_reserva; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estado_reserva (
    codigo character varying(5) NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.estado_reserva OWNER TO postgres;

--
-- Name: estado_salon; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estado_salon (
    codigo character varying(5) NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.estado_salon OWNER TO postgres;

--
-- Name: inventario_equipa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventario_equipa (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    equipamiento_id bigint NOT NULL,
    estado_equipa_id character varying(5) NOT NULL
);


ALTER TABLE public.inventario_equipa OWNER TO postgres;

--
-- Name: inventario_equipa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventario_equipa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_equipa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario_mobil; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventario_mobil (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    estado_mobil_id character varying(5) NOT NULL,
    mobiliario_id bigint NOT NULL
);


ALTER TABLE public.inventario_mobil OWNER TO postgres;

--
-- Name: inventario_mobil_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventario_mobil ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_mobil_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metodo_pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metodo_pago (
    codigo character varying(5) NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.metodo_pago OWNER TO postgres;

--
-- Name: mobiliario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mobiliario (
    id bigint NOT NULL,
    nombre character varying(75) NOT NULL,
    descripcion character varying(550) NOT NULL,
    costo numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    tipo_movil_id bigint NOT NULL
);


ALTER TABLE public.mobiliario OWNER TO postgres;

--
-- Name: mobiliario_descripcion_mob; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mobiliario_descripcion_mob (
    id bigint NOT NULL,
    mobiliario_id bigint NOT NULL,
    caractermobil_id bigint NOT NULL
);


ALTER TABLE public.mobiliario_descripcion_mob OWNER TO postgres;

--
-- Name: mobiliario_descripcion_mob_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mobiliario_descripcion_mob ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mobiliario_descripcion_mob_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mobiliario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mobiliario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mobiliario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: montaje; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.montaje (
    id bigint NOT NULL,
    costo numeric(10,2) NOT NULL,
    salon_id bigint NOT NULL,
    tipo_montaje_id bigint NOT NULL
);


ALTER TABLE public.montaje OWNER TO postgres;

--
-- Name: montaje_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.montaje ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.montaje_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: montaje_mobilairio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.montaje_mobilairio (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    completado boolean NOT NULL,
    mobiliario_id bigint NOT NULL,
    montaje_id bigint NOT NULL
);


ALTER TABLE public.montaje_mobilairio OWNER TO postgres;

--
-- Name: montaje_mobilairio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.montaje_mobilairio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.montaje_mobilairio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pago (
    id bigint NOT NULL,
    nota character varying(100) NOT NULL,
    monto numeric(10,2) NOT NULL,
    fecha date NOT NULL,
    hora time without time zone NOT NULL,
    no_pago integer NOT NULL,
    concepto_pago_id character varying(5) NOT NULL,
    metodo_pago_id character varying(5) NOT NULL,
    reservacion_id bigint NOT NULL,
    saldo numeric(10,2) NOT NULL
);


ALTER TABLE public.pago OWNER TO postgres;

--
-- Name: pago_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registr_esta_reserva; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registr_esta_reserva (
    id bigint NOT NULL,
    fecha date NOT NULL,
    estado_reserva_id character varying(5) NOT NULL,
    reservacion_id bigint NOT NULL
);


ALTER TABLE public.registr_esta_reserva OWNER TO postgres;

--
-- Name: registr_esta_reserva_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registr_esta_reserva ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registr_esta_reserva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registr_esta_salon; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registr_esta_salon (
    id bigint NOT NULL,
    fecha date NOT NULL,
    estado_salon_id character varying(5) NOT NULL,
    salon_id bigint NOT NULL
);


ALTER TABLE public.registr_esta_salon OWNER TO postgres;

--
-- Name: registr_esta_salon_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registr_esta_salon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registr_esta_salon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reserva_equipa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reserva_equipa (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    equipamiento_id bigint NOT NULL,
    reservacion_id bigint NOT NULL
);


ALTER TABLE public.reserva_equipa OWNER TO postgres;

--
-- Name: reserva_equipa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reserva_equipa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reserva_equipa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservacion (
    id bigint NOT NULL,
    "descripEvento" character varying(550) NOT NULL,
    "estimaAsistentes" integer NOT NULL,
    "fechaReservacion" date NOT NULL,
    "fechaEvento" date NOT NULL,
    "horaInicio" time without time zone NOT NULL,
    "horaFin" time without time zone NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    "IVA" numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    cliente_id bigint NOT NULL,
    estado_reserva_id character varying(5) NOT NULL,
    montaje_id bigint NOT NULL,
    tipo_evento_id bigint NOT NULL,
    "nombreEvento" character varying(100)
);


ALTER TABLE public.reservacion OWNER TO postgres;

--
-- Name: reservacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservacion_reserva_servicio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservacion_reserva_servicio (
    id bigint NOT NULL,
    reservacion_id bigint NOT NULL,
    servicio_id bigint NOT NULL
);


ALTER TABLE public.reservacion_reserva_servicio OWNER TO postgres;

--
-- Name: reservacion_reserva_servicio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservacion_reserva_servicio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservacion_reserva_servicio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservacion_traba_reserva; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservacion_traba_reserva (
    id bigint NOT NULL,
    reservacion_id bigint NOT NULL,
    trabajador_id character varying(10) NOT NULL
);


ALTER TABLE public.reservacion_traba_reserva OWNER TO postgres;

--
-- Name: reservacion_traba_reserva_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservacion_traba_reserva ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservacion_traba_reserva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    codigo character varying(5) NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- Name: salon; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.salon (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    costo numeric(10,2) NOT NULL,
    ubicacion character varying(100) NOT NULL,
    "dimenLargo" numeric(10,2) NOT NULL,
    "dimenAncho" numeric(10,2) NOT NULL,
    "dimenAlto" numeric(10,2) NOT NULL,
    "metrosCuadrados" numeric(10,2) NOT NULL,
    "maxCapacidad" integer NOT NULL,
    estado_salon_id character varying(5) NOT NULL
);


ALTER TABLE public.salon OWNER TO postgres;

--
-- Name: salon_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.salon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.salon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.servicio (
    id bigint NOT NULL,
    nombre character varying(75) NOT NULL,
    descripcion character varying(550) NOT NULL,
    costo numeric(10,2) NOT NULL,
    disposicion boolean NOT NULL,
    tipo_servicio_id bigint NOT NULL
);


ALTER TABLE public.servicio OWNER TO postgres;

--
-- Name: servicio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.servicio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servicio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_cliente (
    codigo character varying(5) NOT NULL,
    nombre character varying(100) NOT NULL,
    disposicion boolean NOT NULL
);


ALTER TABLE public.tipo_cliente OWNER TO postgres;

--
-- Name: tipo_equipa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_equipa (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    disposicion boolean NOT NULL
);


ALTER TABLE public.tipo_equipa OWNER TO postgres;

--
-- Name: tipo_equipa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_equipa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_equipa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_evento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_evento (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    disposicion boolean NOT NULL
);


ALTER TABLE public.tipo_evento OWNER TO postgres;

--
-- Name: tipo_evento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_mobil; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_mobil (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    disposicion boolean NOT NULL
);


ALTER TABLE public.tipo_mobil OWNER TO postgres;

--
-- Name: tipo_mobil_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_mobil ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_mobil_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_montaje; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_montaje (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    disposicion boolean NOT NULL
);


ALTER TABLE public.tipo_montaje OWNER TO postgres;

--
-- Name: tipo_montaje_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_montaje ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_montaje_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_servicio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_servicio (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion character varying(550) NOT NULL,
    disposicion boolean NOT NULL
);


ALTER TABLE public.tipo_servicio OWNER TO postgres;

--
-- Name: tipo_servicio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_servicio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_servicio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trabajador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trabajador (
    no_empleado character varying(10) NOT NULL,
    rfc character varying(13) NOT NULL,
    nombre_fiscal character varying(150) NOT NULL,
    nombre character varying(150) NOT NULL,
    "apellidoPaterno" character varying(150) NOT NULL,
    "apelidoMaterno" character varying(150) NOT NULL,
    telefono character varying(15) NOT NULL,
    correo_electronico character varying(254) NOT NULL,
    cuenta_id bigint NOT NULL,
    rol_id character varying(5) NOT NULL
);


ALTER TABLE public.trabajador OWNER TO postgres;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Tipo de servicio	12	add_tiposervicio
26	Can change Tipo de servicio	12	change_tiposervicio
27	Can delete Tipo de servicio	12	delete_tiposervicio
28	Can view Tipo de servicio	12	view_tiposervicio
29	Can add Estado de cuenta	9	add_estadocuenta
30	Can change Estado de cuenta	9	change_estadocuenta
31	Can delete Estado de cuenta	9	delete_estadocuenta
32	Can view Estado de cuenta	9	view_estadocuenta
33	Can add Rol	10	add_rol
34	Can change Rol	10	change_rol
35	Can delete Rol	10	delete_rol
36	Can view Rol	10	view_rol
37	Can add Tipo de cliente	11	add_tipocliente
38	Can change Tipo de cliente	11	change_tipocliente
39	Can delete Tipo de cliente	11	delete_tipocliente
40	Can view Tipo de cliente	11	view_tipocliente
41	Can add Cuenta	7	add_cuenta
42	Can change Cuenta	7	change_cuenta
43	Can delete Cuenta	7	delete_cuenta
44	Can view Cuenta	7	view_cuenta
45	Can add Datos del cliente	8	add_datoscliente
46	Can change Datos del cliente	8	change_datoscliente
47	Can delete Datos del cliente	8	delete_datoscliente
48	Can view Datos del cliente	8	view_datoscliente
49	Can add Trabajador	13	add_trabajador
50	Can change Trabajador	13	change_trabajador
51	Can delete Trabajador	13	delete_trabajador
52	Can view Trabajador	13	view_trabajador
53	Can add Estado de mobiliario	19	add_estadomobil
54	Can change Estado de mobiliario	19	change_estadomobil
55	Can delete Estado de mobiliario	19	delete_estadomobil
56	Can view Estado de mobiliario	19	view_estadomobil
57	Can add Tipo de evento	36	add_tipoevento
58	Can change Tipo de evento	36	change_tipoevento
59	Can delete Tipo de evento	36	delete_tipoevento
60	Can view Tipo de evento	36	view_tipoevento
61	Can add Registro de estados de Salon	30	add_registrestadsalon
62	Can change Registro de estados de Salon	30	change_registrestadsalon
63	Can delete Registro de estados de Salon	30	delete_registrestadsalon
64	Can view Registro de estados de Salon	30	view_registrestadsalon
65	Can add Mobiliarios de un Montaje	27	add_montajemobiliario
66	Can change Mobiliarios de un Montaje	27	change_montajemobiliario
67	Can delete Mobiliarios de un Montaje	27	delete_montajemobiliario
68	Can view Mobiliarios de un Montaje	27	view_montajemobiliario
69	Can add Equipamientos de Reserva	32	add_reservaequipa
70	Can change Equipamientos de Reserva	32	change_reservaequipa
71	Can delete Equipamientos de Reserva	32	delete_reservaequipa
72	Can view Equipamientos de Reserva	32	view_reservaequipa
73	Can add Equipamiento	17	add_equipamiento
74	Can change Equipamiento	17	change_equipamiento
75	Can delete Equipamiento	17	delete_equipamiento
76	Can view Equipamiento	17	view_equipamiento
77	Can add Estado de equipamiento	18	add_estadoequipa
78	Can change Estado de equipamiento	18	change_estadoequipa
79	Can delete Estado de equipamiento	18	delete_estadoequipa
80	Can view Estado de equipamiento	18	view_estadoequipa
81	Can add Tipo de mobiliario	37	add_tipomobil
82	Can change Tipo de mobiliario	37	change_tipomobil
83	Can delete Tipo de mobiliario	37	delete_tipomobil
84	Can view Tipo de mobiliario	37	view_tipomobil
85	Can add Tipo de montaje	38	add_tipomontaje
86	Can change Tipo de montaje	38	change_tipomontaje
87	Can delete Tipo de montaje	38	delete_tipomontaje
88	Can view Tipo de montaje	38	view_tipomontaje
89	Can add Pago	28	add_pago
90	Can change Pago	28	change_pago
91	Can delete Pago	28	delete_pago
92	Can view Pago	28	view_pago
93	Can add Montaje	26	add_montaje
94	Can change Montaje	26	change_montaje
95	Can delete Montaje	26	delete_montaje
96	Can view Montaje	26	view_montaje
97	Can add Registro de estados de Reservacion	29	add_registrestadreserva
98	Can change Registro de estados de Reservacion	29	change_registrestadreserva
99	Can delete Registro de estados de Reservacion	29	delete_registrestadreserva
100	Can view Registro de estados de Reservacion	29	view_registrestadreserva
101	Can add Método de pago	24	add_metodopago
102	Can change Método de pago	24	change_metodopago
103	Can delete Método de pago	24	delete_metodopago
104	Can view Método de pago	24	view_metodopago
105	Can add Estado de reserva	20	add_estadoreserva
106	Can change Estado de reserva	20	change_estadoreserva
107	Can delete Estado de reserva	20	delete_estadoreserva
108	Can view Estado de reserva	20	view_estadoreserva
109	Can add Reservacion	31	add_reservacion
110	Can change Reservacion	31	change_reservacion
111	Can delete Reservacion	31	delete_reservacion
112	Can view Reservacion	31	view_reservacion
113	Can add Concepto de pago	15	add_conceptopago
114	Can change Concepto de pago	15	change_conceptopago
115	Can delete Concepto de pago	15	delete_conceptopago
116	Can view Concepto de pago	15	view_conceptopago
117	Can add Tipo de equipamiento	35	add_tipoequipa
118	Can change Tipo de equipamiento	35	change_tipoequipa
119	Can delete Tipo de equipamiento	35	delete_tipoequipa
120	Can view Tipo de equipamiento	35	view_tipoequipa
121	Can add Salon	33	add_salon
122	Can change Salon	33	change_salon
123	Can delete Salon	33	delete_salon
124	Can view Salon	33	view_salon
125	Can add Estado de Mobilarios	23	add_inventariomob
126	Can change Estado de Mobilarios	23	change_inventariomob
127	Can delete Estado de Mobilarios	23	delete_inventariomob
128	Can view Estado de Mobilarios	23	view_inventariomob
129	Can add Servicio	34	add_servicio
130	Can change Servicio	34	change_servicio
131	Can delete Servicio	34	delete_servicio
132	Can view Servicio	34	view_servicio
133	Can add Encuesta	16	add_encuesta
134	Can change Encuesta	16	change_encuesta
135	Can delete Encuesta	16	delete_encuesta
136	Can view Encuesta	16	view_encuesta
137	Can add Característica de mobiliario	14	add_caractermobil
138	Can change Característica de mobiliario	14	change_caractermobil
139	Can delete Característica de mobiliario	14	delete_caractermobil
140	Can view Característica de mobiliario	14	view_caractermobil
141	Can add Mobiliario	25	add_mobiliario
142	Can change Mobiliario	25	change_mobiliario
143	Can delete Mobiliario	25	delete_mobiliario
144	Can view Mobiliario	25	view_mobiliario
145	Can add Estado de salón	21	add_estadosalon
146	Can change Estado de salón	21	change_estadosalon
147	Can delete Estado de salón	21	delete_estadosalon
148	Can view Estado de salón	21	view_estadosalon
149	Can add Estado de Equipamientos	22	add_inventarioequipa
150	Can change Estado de Equipamientos	22	change_inventarioequipa
151	Can delete Estado de Equipamientos	22	delete_inventarioequipa
152	Can view Estado de Equipamientos	22	view_inventarioequipa
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$Rl7piK3pq6dgtPs3PociOH$T9aJsi+5wGbjeAMPUGWEijNK8Z+f3NeNmf6W+NLTn7Y=	2026-03-24 20:43:38.707182-07	t	gallardo			luisdagallardo@gmail.com	t	t	2026-03-21 19:01:43.529756-07
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: caracter_mobi; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.caracter_mobi (id, descripcion) FROM stdin;
\.


--
-- Data for Name: concepto_pago; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.concepto_pago (codigo, nombre) FROM stdin;
ABONO	Abono
LIQUI	Liquidación
UNICO	Pago único
\.


--
-- Data for Name: cuenta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuenta (id, nombre_usuario, correo_electronico, disposicion, estado_cuenta_id, firebase_uid) FROM stdin;
1	luis	luisdagallardo@gmail.com	t	ACT	7A2duPu23vQuxZMLc0xxp2ZS9VX2
2	cliente_ejemplo	cliente_ejemplo@email.com	t	ACT	\N
3	Tomas	zuanperg@gmail.com	t	ACT	IdJro4ye63OFMuMzgheGd8G0n5h2
\.


--
-- Data for Name: datos_cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.datos_cliente (id, rfc, nombre_fiscal, nombre, "apellidoPaterno", "apelidoMaterno", telefono, correo_electronico, dir_colonia, dir_calle, dir_numero, cuenta_id, tipo_cliente_id) FROM stdin;
1	XAXX010101000	Juan Pérez López	Juan	Pérez	López	5551234567	cliente_ejemplo@email.com	Centro	Av. Principal	123	2	PF
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-03-21 19:04:21.380615-07	1	luisdagallardo@gmail.com	1	[{"added": {}}]	7	1
2	2026-03-21 19:05:26.609504-07	12345	12345	1	[{"added": {}}]	13	1
3	2026-03-23 21:20:02.720717-07	3	zuanperg@gmail.com	1	[{"added": {}}]	7	1
4	2026-03-23 21:21:23.556943-07	T-1235	T-1235	1	[{"added": {}}]	13	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	BookingRoomApp	cuenta
8	BookingRoomApp	datoscliente
9	BookingRoomApp	estadocuenta
10	BookingRoomApp	rol
11	BookingRoomApp	tipocliente
12	BookingRoomApp	tiposervicio
13	BookingRoomApp	trabajador
14	BookingRoomApp	caractermobil
15	BookingRoomApp	conceptopago
16	BookingRoomApp	encuesta
17	BookingRoomApp	equipamiento
18	BookingRoomApp	estadoequipa
19	BookingRoomApp	estadomobil
20	BookingRoomApp	estadoreserva
21	BookingRoomApp	estadosalon
22	BookingRoomApp	inventarioequipa
23	BookingRoomApp	inventariomob
24	BookingRoomApp	metodopago
25	BookingRoomApp	mobiliario
26	BookingRoomApp	montaje
27	BookingRoomApp	montajemobiliario
28	BookingRoomApp	pago
29	BookingRoomApp	registrestadreserva
30	BookingRoomApp	registrestadsalon
31	BookingRoomApp	reservacion
32	BookingRoomApp	reservaequipa
33	BookingRoomApp	salon
34	BookingRoomApp	servicio
35	BookingRoomApp	tipoequipa
36	BookingRoomApp	tipoevento
37	BookingRoomApp	tipomobil
38	BookingRoomApp	tipomontaje
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	BookingRoomApp	0001_initial	2026-03-21 18:51:25.561656-07
2	BookingRoomApp	0002_estadocuenta_rol_tipocliente_cuenta_datoscliente_and_more	2026-03-21 18:51:25.618855-07
3	BookingRoomApp	0003_tipocliente_disposicion	2026-03-21 18:51:25.626087-07
4	BookingRoomApp	0004_cuenta_firebase_uid_alter_cuenta_correo_electronico_and_more	2026-03-21 18:51:25.65995-07
5	BookingRoomApp	0005_alter_rol_nombre	2026-03-21 18:51:25.667537-07
6	contenttypes	0001_initial	2026-03-21 18:51:25.676583-07
7	auth	0001_initial	2026-03-21 18:51:25.730946-07
8	admin	0001_initial	2026-03-21 18:51:25.751866-07
9	admin	0002_logentry_remove_auto_add	2026-03-21 18:51:25.766812-07
10	admin	0003_logentry_add_action_flag_choices	2026-03-21 18:51:25.776627-07
11	contenttypes	0002_remove_content_type_name	2026-03-21 18:51:25.802866-07
12	auth	0002_alter_permission_name_max_length	2026-03-21 18:51:25.815003-07
13	auth	0003_alter_user_email_max_length	2026-03-21 18:51:25.827903-07
14	auth	0004_alter_user_username_opts	2026-03-21 18:51:25.836539-07
15	auth	0005_alter_user_last_login_null	2026-03-21 18:51:25.847907-07
16	auth	0006_require_contenttypes_0002	2026-03-21 18:51:25.849998-07
17	auth	0007_alter_validators_add_error_messages	2026-03-21 18:51:25.860775-07
18	auth	0008_alter_user_username_max_length	2026-03-21 18:51:25.87411-07
19	auth	0009_alter_user_last_name_max_length	2026-03-21 18:51:25.887246-07
20	auth	0010_alter_group_name_max_length	2026-03-21 18:51:25.900918-07
21	auth	0011_update_proxy_permissions	2026-03-21 18:51:25.915679-07
22	auth	0012_alter_user_first_name_max_length	2026-03-21 18:51:25.926295-07
23	sessions	0001_initial	2026-03-21 18:51:25.934042-07
24	BookingRoomApp	0006_caractermobil_conceptopago_equipamiento_estadoequipa_and_more	2026-03-23 17:36:09.946969-07
25	BookingRoomApp	0007_pago_saldo_reservacion_nombreevento_and_more	2026-03-23 23:33:13.672678-07
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: encuesta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.encuesta (id, personal, equipamiento, servicios, salon, mobiliario, reservacion_id) FROM stdin;
\.


--
-- Data for Name: equipamiento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.equipamiento (id, nombre, descripcion, costo, stock, tipo_equipa_id) FROM stdin;
\.


--
-- Data for Name: estado_cuenta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estado_cuenta (codigo, nombre) FROM stdin;
ACT	Activo
INC	Inactivo
\.


--
-- Data for Name: estado_equipa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estado_equipa (codigo, nombre) FROM stdin;
\.


--
-- Data for Name: estado_mobil; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estado_mobil (codigo, nombre) FROM stdin;
\.


--
-- Data for Name: estado_reserva; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estado_reserva (codigo, nombre) FROM stdin;
PEN	Pendiente
CON	Confirmada
CAN	Cancelada
FIN	Finalizada
\.


--
-- Data for Name: estado_salon; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estado_salon (codigo, nombre) FROM stdin;
DIS	Disponible
OCU	Ocupado
MAN	En mantenimiento
\.


--
-- Data for Name: inventario_equipa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventario_equipa (id, cantidad, equipamiento_id, estado_equipa_id) FROM stdin;
\.


--
-- Data for Name: inventario_mobil; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventario_mobil (id, cantidad, estado_mobil_id, mobiliario_id) FROM stdin;
\.


--
-- Data for Name: metodo_pago; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.metodo_pago (codigo, nombre) FROM stdin;
EFECT	Efectivo
TARJE	Tarjeta
NFC	NFC
TRANS	Transferencia
\.


--
-- Data for Name: mobiliario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mobiliario (id, nombre, descripcion, costo, stock, tipo_movil_id) FROM stdin;
\.


--
-- Data for Name: mobiliario_descripcion_mob; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mobiliario_descripcion_mob (id, mobiliario_id, caractermobil_id) FROM stdin;
\.


--
-- Data for Name: montaje; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.montaje (id, costo, salon_id, tipo_montaje_id) FROM stdin;
1	2000.00	1	3
\.


--
-- Data for Name: montaje_mobilairio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.montaje_mobilairio (id, cantidad, completado, mobiliario_id, montaje_id) FROM stdin;
\.


--
-- Data for Name: pago; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pago (id, nota, monto, fecha, hora, no_pago, concepto_pago_id, metodo_pago_id, reservacion_id, saldo) FROM stdin;
1	Primer pago de juan	5000.00	2026-03-24	06:56:57.200505	1	ABONO	EFECT	1	3120.00
\.


--
-- Data for Name: registr_esta_reserva; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.registr_esta_reserva (id, fecha, estado_reserva_id, reservacion_id) FROM stdin;
\.


--
-- Data for Name: registr_esta_salon; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.registr_esta_salon (id, fecha, estado_salon_id, salon_id) FROM stdin;
\.


--
-- Data for Name: reserva_equipa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reserva_equipa (id, cantidad, equipamiento_id, reservacion_id) FROM stdin;
\.


--
-- Data for Name: reservacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservacion (id, "descripEvento", "estimaAsistentes", "fechaReservacion", "fechaEvento", "horaInicio", "horaFin", subtotal, "IVA", total, cliente_id, estado_reserva_id, montaje_id, tipo_evento_id, "nombreEvento") FROM stdin;
1	Cumpleaños de Figueroa	50	2026-03-24	2026-04-15	18:00:00	23:00:00	7000.00	1120.00	8120.00	1	PEN	1	2	lolsete
\.


--
-- Data for Name: reservacion_reserva_servicio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservacion_reserva_servicio (id, reservacion_id, servicio_id) FROM stdin;
\.


--
-- Data for Name: reservacion_traba_reserva; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservacion_traba_reserva (id, reservacion_id, trabajador_id) FROM stdin;
\.


--
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (codigo, nombre) FROM stdin;
ADMIN	Administrador
ALMAC	Almacenista
RECEP	Recepcionista
COORD	Coordinador
\.


--
-- Data for Name: salon; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.salon (id, nombre, costo, ubicacion, "dimenLargo", "dimenAncho", "dimenAlto", "metrosCuadrados", "maxCapacidad", estado_salon_id) FROM stdin;
1	Salón Principal	5000.00	Piso 1	20.00	15.00	4.00	300.00	200	DIS
\.


--
-- Data for Name: servicio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.servicio (id, nombre, descripcion, costo, disposicion, tipo_servicio_id) FROM stdin;
\.


--
-- Data for Name: tipo_cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_cliente (codigo, nombre, disposicion) FROM stdin;
PM	Persona Moral	t
PF	Persona Física	t
\.


--
-- Data for Name: tipo_equipa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_equipa (id, nombre, disposicion) FROM stdin;
\.


--
-- Data for Name: tipo_evento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_evento (id, nombre, disposicion) FROM stdin;
1	Boda	t
2	Cumpleaños	t
3	Corporativo	t
4	Conferencia	t
5	Reunión	t
\.


--
-- Data for Name: tipo_mobil; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_mobil (id, nombre, disposicion) FROM stdin;
\.


--
-- Data for Name: tipo_montaje; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_montaje (id, nombre, disposicion) FROM stdin;
1	Teatro	t
2	Escuela	t
3	Banquete	t
4	Cocktail	t
5	U	t
\.


--
-- Data for Name: tipo_servicio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_servicio (id, nombre, descripcion, disposicion) FROM stdin;
\.


--
-- Data for Name: trabajador; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trabajador (no_empleado, rfc, nombre_fiscal, nombre, "apellidoPaterno", "apelidoMaterno", telefono, correo_electronico, cuenta_id, rol_id) FROM stdin;
12345	1234567890ABC	Luis David Gallardo Ramirez	Luis David	Gallardo	Ramirez	6632081698	luisdagallardo@gmail.com	1	ALMAC
T-1235	ABCABCABC123	Tomas Garcia Mariño	Tomas	Garcia	Mariño	6672001190	zuanperg@gmail.com	3	ADMIN
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 152, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: caracter_mobi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.caracter_mobi_id_seq', 1, false);


--
-- Name: cuenta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuenta_id_seq', 4, true);


--
-- Name: datos_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.datos_cliente_id_seq', 1, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 4, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 38, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: encuesta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.encuesta_id_seq', 1, false);


--
-- Name: equipamiento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.equipamiento_id_seq', 1, false);


--
-- Name: inventario_equipa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventario_equipa_id_seq', 1, false);


--
-- Name: inventario_mobil_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventario_mobil_id_seq', 1, false);


--
-- Name: mobiliario_descripcion_mob_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mobiliario_descripcion_mob_id_seq', 1, false);


--
-- Name: mobiliario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mobiliario_id_seq', 1, false);


--
-- Name: montaje_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.montaje_id_seq', 1, true);


--
-- Name: montaje_mobilairio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.montaje_mobilairio_id_seq', 1, false);


--
-- Name: pago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pago_id_seq', 1, true);


--
-- Name: registr_esta_reserva_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.registr_esta_reserva_id_seq', 1, false);


--
-- Name: registr_esta_salon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.registr_esta_salon_id_seq', 1, false);


--
-- Name: reserva_equipa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reserva_equipa_id_seq', 1, false);


--
-- Name: reservacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservacion_id_seq', 1, true);


--
-- Name: reservacion_reserva_servicio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservacion_reserva_servicio_id_seq', 1, false);


--
-- Name: reservacion_traba_reserva_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservacion_traba_reserva_id_seq', 1, false);


--
-- Name: salon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.salon_id_seq', 1, true);


--
-- Name: servicio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.servicio_id_seq', 1, false);


--
-- Name: tipo_equipa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_equipa_id_seq', 1, false);


--
-- Name: tipo_evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_evento_id_seq', 5, true);


--
-- Name: tipo_mobil_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_mobil_id_seq', 1, false);


--
-- Name: tipo_montaje_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_montaje_id_seq', 5, true);


--
-- Name: tipo_servicio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_servicio_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: caracter_mobi caracter_mobi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caracter_mobi
    ADD CONSTRAINT caracter_mobi_pkey PRIMARY KEY (id);


--
-- Name: concepto_pago concepto_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.concepto_pago
    ADD CONSTRAINT concepto_pago_pkey PRIMARY KEY (codigo);


--
-- Name: cuenta cuenta_correo_electronico_27870941_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_correo_electronico_27870941_uniq UNIQUE (correo_electronico);


--
-- Name: cuenta cuenta_firebase_uid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_firebase_uid_key UNIQUE (firebase_uid);


--
-- Name: cuenta cuenta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_pkey PRIMARY KEY (id);


--
-- Name: datos_cliente datos_cliente_correo_electronico_a27faeb9_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datos_cliente
    ADD CONSTRAINT datos_cliente_correo_electronico_a27faeb9_uniq UNIQUE (correo_electronico);


--
-- Name: datos_cliente datos_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datos_cliente
    ADD CONSTRAINT datos_cliente_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: encuesta encuesta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.encuesta
    ADD CONSTRAINT encuesta_pkey PRIMARY KEY (id);


--
-- Name: equipamiento equipamiento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipamiento
    ADD CONSTRAINT equipamiento_pkey PRIMARY KEY (id);


--
-- Name: estado_cuenta estado_cuenta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estado_cuenta
    ADD CONSTRAINT estado_cuenta_pkey PRIMARY KEY (codigo);


--
-- Name: estado_equipa estado_equipa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estado_equipa
    ADD CONSTRAINT estado_equipa_pkey PRIMARY KEY (codigo);


--
-- Name: inventario_equipa estado_equipamiento; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_equipa
    ADD CONSTRAINT estado_equipamiento UNIQUE (equipamiento_id, estado_equipa_id);


--
-- Name: estado_mobil estado_mobil_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estado_mobil
    ADD CONSTRAINT estado_mobil_pkey PRIMARY KEY (codigo);


--
-- Name: inventario_mobil estado_mobiliario; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_mobil
    ADD CONSTRAINT estado_mobiliario UNIQUE (mobiliario_id, estado_mobil_id);


--
-- Name: estado_reserva estado_reserva_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estado_reserva
    ADD CONSTRAINT estado_reserva_pkey PRIMARY KEY (codigo);


--
-- Name: estado_salon estado_salon_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estado_salon
    ADD CONSTRAINT estado_salon_pkey PRIMARY KEY (codigo);


--
-- Name: inventario_equipa inventario_equipa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_equipa
    ADD CONSTRAINT inventario_equipa_pkey PRIMARY KEY (id);


--
-- Name: inventario_mobil inventario_mobil_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_mobil
    ADD CONSTRAINT inventario_mobil_pkey PRIMARY KEY (id);


--
-- Name: metodo_pago metodo_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metodo_pago
    ADD CONSTRAINT metodo_pago_pkey PRIMARY KEY (codigo);


--
-- Name: mobiliario_descripcion_mob mobiliario_descripcion_m_mobiliario_id_caractermo_cb8efdc2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobiliario_descripcion_mob
    ADD CONSTRAINT mobiliario_descripcion_m_mobiliario_id_caractermo_cb8efdc2_uniq UNIQUE (mobiliario_id, caractermobil_id);


--
-- Name: mobiliario_descripcion_mob mobiliario_descripcion_mob_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobiliario_descripcion_mob
    ADD CONSTRAINT mobiliario_descripcion_mob_pkey PRIMARY KEY (id);


--
-- Name: mobiliario mobiliario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobiliario
    ADD CONSTRAINT mobiliario_pkey PRIMARY KEY (id);


--
-- Name: montaje_mobilairio montaje_mobilairio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.montaje_mobilairio
    ADD CONSTRAINT montaje_mobilairio_pkey PRIMARY KEY (id);


--
-- Name: montaje montaje_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.montaje
    ADD CONSTRAINT montaje_pkey PRIMARY KEY (id);


--
-- Name: pago pago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT pago_pkey PRIMARY KEY (id);


--
-- Name: registr_esta_reserva registr_esta_reserva_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registr_esta_reserva
    ADD CONSTRAINT registr_esta_reserva_pkey PRIMARY KEY (id);


--
-- Name: registr_esta_salon registr_esta_salon_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registr_esta_salon
    ADD CONSTRAINT registr_esta_salon_pkey PRIMARY KEY (id);


--
-- Name: reserva_equipa reserva_equipa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva_equipa
    ADD CONSTRAINT reserva_equipa_pkey PRIMARY KEY (id);


--
-- Name: reservacion reservacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion
    ADD CONSTRAINT reservacion_pkey PRIMARY KEY (id);


--
-- Name: reservacion_reserva_servicio reservacion_reserva_serv_reservacion_id_servicio__7cc9409e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion_reserva_servicio
    ADD CONSTRAINT reservacion_reserva_serv_reservacion_id_servicio__7cc9409e_uniq UNIQUE (reservacion_id, servicio_id);


--
-- Name: reservacion_reserva_servicio reservacion_reserva_servicio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion_reserva_servicio
    ADD CONSTRAINT reservacion_reserva_servicio_pkey PRIMARY KEY (id);


--
-- Name: reservacion_traba_reserva reservacion_traba_reserv_reservacion_id_trabajado_264e9084_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion_traba_reserva
    ADD CONSTRAINT reservacion_traba_reserv_reservacion_id_trabajado_264e9084_uniq UNIQUE (reservacion_id, trabajador_id);


--
-- Name: reservacion_traba_reserva reservacion_traba_reserva_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion_traba_reserva
    ADD CONSTRAINT reservacion_traba_reserva_pkey PRIMARY KEY (id);


--
-- Name: rol rol_nombre_ab94fcd3_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_nombre_ab94fcd3_uniq UNIQUE (nombre);


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (codigo);


--
-- Name: salon salon_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.salon
    ADD CONSTRAINT salon_pkey PRIMARY KEY (id);


--
-- Name: servicio servicio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.servicio
    ADD CONSTRAINT servicio_pkey PRIMARY KEY (id);


--
-- Name: tipo_cliente tipo_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_cliente
    ADD CONSTRAINT tipo_cliente_pkey PRIMARY KEY (codigo);


--
-- Name: tipo_equipa tipo_equipa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_equipa
    ADD CONSTRAINT tipo_equipa_pkey PRIMARY KEY (id);


--
-- Name: tipo_evento tipo_evento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_evento
    ADD CONSTRAINT tipo_evento_pkey PRIMARY KEY (id);


--
-- Name: tipo_mobil tipo_mobil_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_mobil
    ADD CONSTRAINT tipo_mobil_pkey PRIMARY KEY (id);


--
-- Name: tipo_montaje tipo_montaje_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_montaje
    ADD CONSTRAINT tipo_montaje_pkey PRIMARY KEY (id);


--
-- Name: tipo_servicio tipo_servicio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_servicio
    ADD CONSTRAINT tipo_servicio_pkey PRIMARY KEY (id);


--
-- Name: trabajador trabajador_correo_electronico_004573a2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trabajador
    ADD CONSTRAINT trabajador_correo_electronico_004573a2_uniq UNIQUE (correo_electronico);


--
-- Name: trabajador trabajador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trabajador
    ADD CONSTRAINT trabajador_pkey PRIMARY KEY (no_empleado);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: concepto_pago_codigo_2fc6a8f8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX concepto_pago_codigo_2fc6a8f8_like ON public.concepto_pago USING btree (codigo varchar_pattern_ops);


--
-- Name: cuenta_correo_electronico_27870941_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuenta_correo_electronico_27870941_like ON public.cuenta USING btree (correo_electronico varchar_pattern_ops);


--
-- Name: cuenta_estado_cuenta_id_da82fe13; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuenta_estado_cuenta_id_da82fe13 ON public.cuenta USING btree (estado_cuenta_id);


--
-- Name: cuenta_estado_cuenta_id_da82fe13_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuenta_estado_cuenta_id_da82fe13_like ON public.cuenta USING btree (estado_cuenta_id varchar_pattern_ops);


--
-- Name: cuenta_firebase_uid_1388a828_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuenta_firebase_uid_1388a828_like ON public.cuenta USING btree (firebase_uid varchar_pattern_ops);


--
-- Name: datos_cliente_correo_electronico_a27faeb9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX datos_cliente_correo_electronico_a27faeb9_like ON public.datos_cliente USING btree (correo_electronico varchar_pattern_ops);


--
-- Name: datos_cliente_cuenta_id_1a241c4e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX datos_cliente_cuenta_id_1a241c4e ON public.datos_cliente USING btree (cuenta_id);


--
-- Name: datos_cliente_tipo_cliente_id_b573971f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX datos_cliente_tipo_cliente_id_b573971f ON public.datos_cliente USING btree (tipo_cliente_id);


--
-- Name: datos_cliente_tipo_cliente_id_b573971f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX datos_cliente_tipo_cliente_id_b573971f_like ON public.datos_cliente USING btree (tipo_cliente_id varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: encuesta_reservacion_id_9bbd360d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX encuesta_reservacion_id_9bbd360d ON public.encuesta USING btree (reservacion_id);


--
-- Name: equipamiento_tipo_equipa_id_6021d437; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX equipamiento_tipo_equipa_id_6021d437 ON public.equipamiento USING btree (tipo_equipa_id);


--
-- Name: estado_cuenta_codigo_b8d7e8c6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX estado_cuenta_codigo_b8d7e8c6_like ON public.estado_cuenta USING btree (codigo varchar_pattern_ops);


--
-- Name: estado_equipa_codigo_1390871c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX estado_equipa_codigo_1390871c_like ON public.estado_equipa USING btree (codigo varchar_pattern_ops);


--
-- Name: estado_mobil_codigo_b054b6a0_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX estado_mobil_codigo_b054b6a0_like ON public.estado_mobil USING btree (codigo varchar_pattern_ops);


--
-- Name: estado_reserva_codigo_514f7533_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX estado_reserva_codigo_514f7533_like ON public.estado_reserva USING btree (codigo varchar_pattern_ops);


--
-- Name: estado_salon_codigo_b7fe9670_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX estado_salon_codigo_b7fe9670_like ON public.estado_salon USING btree (codigo varchar_pattern_ops);


--
-- Name: inventario_equipa_equipamiento_id_919efa50; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_equipa_equipamiento_id_919efa50 ON public.inventario_equipa USING btree (equipamiento_id);


--
-- Name: inventario_equipa_estado_equipa_id_08c3eee0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_equipa_estado_equipa_id_08c3eee0 ON public.inventario_equipa USING btree (estado_equipa_id);


--
-- Name: inventario_equipa_estado_equipa_id_08c3eee0_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_equipa_estado_equipa_id_08c3eee0_like ON public.inventario_equipa USING btree (estado_equipa_id varchar_pattern_ops);


--
-- Name: inventario_mobil_estado_mobil_id_63c376f7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_mobil_estado_mobil_id_63c376f7 ON public.inventario_mobil USING btree (estado_mobil_id);


--
-- Name: inventario_mobil_estado_mobil_id_63c376f7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_mobil_estado_mobil_id_63c376f7_like ON public.inventario_mobil USING btree (estado_mobil_id varchar_pattern_ops);


--
-- Name: inventario_mobil_mobiliario_id_bdd44c7b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventario_mobil_mobiliario_id_bdd44c7b ON public.inventario_mobil USING btree (mobiliario_id);


--
-- Name: metodo_pago_codigo_c19229b9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX metodo_pago_codigo_c19229b9_like ON public.metodo_pago USING btree (codigo varchar_pattern_ops);


--
-- Name: mobiliario_descripcion_mob_caractermobil_id_2dbdf09e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mobiliario_descripcion_mob_caractermobil_id_2dbdf09e ON public.mobiliario_descripcion_mob USING btree (caractermobil_id);


--
-- Name: mobiliario_descripcion_mob_mobiliario_id_4edf83ce; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mobiliario_descripcion_mob_mobiliario_id_4edf83ce ON public.mobiliario_descripcion_mob USING btree (mobiliario_id);


--
-- Name: mobiliario_tipo_movil_id_56c345c4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mobiliario_tipo_movil_id_56c345c4 ON public.mobiliario USING btree (tipo_movil_id);


--
-- Name: montaje_mobilairio_mobiliario_id_c96f85b8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX montaje_mobilairio_mobiliario_id_c96f85b8 ON public.montaje_mobilairio USING btree (mobiliario_id);


--
-- Name: montaje_mobilairio_montaje_id_01d9cb23; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX montaje_mobilairio_montaje_id_01d9cb23 ON public.montaje_mobilairio USING btree (montaje_id);


--
-- Name: montaje_salon_id_b5f87ced; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX montaje_salon_id_b5f87ced ON public.montaje USING btree (salon_id);


--
-- Name: montaje_tipo_montaje_id_9d5bfdc9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX montaje_tipo_montaje_id_9d5bfdc9 ON public.montaje USING btree (tipo_montaje_id);


--
-- Name: pago_concepto_pago_id_fd93a518; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pago_concepto_pago_id_fd93a518 ON public.pago USING btree (concepto_pago_id);


--
-- Name: pago_concepto_pago_id_fd93a518_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pago_concepto_pago_id_fd93a518_like ON public.pago USING btree (concepto_pago_id varchar_pattern_ops);


--
-- Name: pago_metodo_pago_id_a0b7dc7c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pago_metodo_pago_id_a0b7dc7c ON public.pago USING btree (metodo_pago_id);


--
-- Name: pago_metodo_pago_id_a0b7dc7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pago_metodo_pago_id_a0b7dc7c_like ON public.pago USING btree (metodo_pago_id varchar_pattern_ops);


--
-- Name: pago_reservacion_id_26479676; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pago_reservacion_id_26479676 ON public.pago USING btree (reservacion_id);


--
-- Name: registr_esta_reserva_estado_reserva_id_644e722d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX registr_esta_reserva_estado_reserva_id_644e722d ON public.registr_esta_reserva USING btree (estado_reserva_id);


--
-- Name: registr_esta_reserva_estado_reserva_id_644e722d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX registr_esta_reserva_estado_reserva_id_644e722d_like ON public.registr_esta_reserva USING btree (estado_reserva_id varchar_pattern_ops);


--
-- Name: registr_esta_reserva_reservacion_id_5fc3eef8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX registr_esta_reserva_reservacion_id_5fc3eef8 ON public.registr_esta_reserva USING btree (reservacion_id);


--
-- Name: registr_esta_salon_estado_salon_id_548a8918; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX registr_esta_salon_estado_salon_id_548a8918 ON public.registr_esta_salon USING btree (estado_salon_id);


--
-- Name: registr_esta_salon_estado_salon_id_548a8918_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX registr_esta_salon_estado_salon_id_548a8918_like ON public.registr_esta_salon USING btree (estado_salon_id varchar_pattern_ops);


--
-- Name: registr_esta_salon_salon_id_adbf1493; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX registr_esta_salon_salon_id_adbf1493 ON public.registr_esta_salon USING btree (salon_id);


--
-- Name: reserva_equipa_equipamiento_id_26d8d847; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reserva_equipa_equipamiento_id_26d8d847 ON public.reserva_equipa USING btree (equipamiento_id);


--
-- Name: reserva_equipa_reservacion_id_0b171f76; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reserva_equipa_reservacion_id_0b171f76 ON public.reserva_equipa USING btree (reservacion_id);


--
-- Name: reservacion_cliente_id_88926292; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservacion_cliente_id_88926292 ON public.reservacion USING btree (cliente_id);


--
-- Name: reservacion_estado_reserva_id_8cb72091; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservacion_estado_reserva_id_8cb72091 ON public.reservacion USING btree (estado_reserva_id);


--
-- Name: reservacion_estado_reserva_id_8cb72091_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservacion_estado_reserva_id_8cb72091_like ON public.reservacion USING btree (estado_reserva_id varchar_pattern_ops);


--
-- Name: reservacion_montaje_id_f3642367; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservacion_montaje_id_f3642367 ON public.reservacion USING btree (montaje_id);


--
-- Name: reservacion_reserva_servicio_reservacion_id_40dd2fd0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservacion_reserva_servicio_reservacion_id_40dd2fd0 ON public.reservacion_reserva_servicio USING btree (reservacion_id);


--
-- Name: reservacion_reserva_servicio_servicio_id_cf6d223a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservacion_reserva_servicio_servicio_id_cf6d223a ON public.reservacion_reserva_servicio USING btree (servicio_id);


--
-- Name: reservacion_tipo_evento_id_fa708b83; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservacion_tipo_evento_id_fa708b83 ON public.reservacion USING btree (tipo_evento_id);


--
-- Name: reservacion_traba_reserva_reservacion_id_646b0526; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservacion_traba_reserva_reservacion_id_646b0526 ON public.reservacion_traba_reserva USING btree (reservacion_id);


--
-- Name: reservacion_traba_reserva_trabajador_id_8a428469; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservacion_traba_reserva_trabajador_id_8a428469 ON public.reservacion_traba_reserva USING btree (trabajador_id);


--
-- Name: reservacion_traba_reserva_trabajador_id_8a428469_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservacion_traba_reserva_trabajador_id_8a428469_like ON public.reservacion_traba_reserva USING btree (trabajador_id varchar_pattern_ops);


--
-- Name: rol_codigo_13ae6e82_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX rol_codigo_13ae6e82_like ON public.rol USING btree (codigo varchar_pattern_ops);


--
-- Name: rol_nombre_ab94fcd3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX rol_nombre_ab94fcd3_like ON public.rol USING btree (nombre varchar_pattern_ops);


--
-- Name: salon_estado_salon_id_f03c9bd4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX salon_estado_salon_id_f03c9bd4 ON public.salon USING btree (estado_salon_id);


--
-- Name: salon_estado_salon_id_f03c9bd4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX salon_estado_salon_id_f03c9bd4_like ON public.salon USING btree (estado_salon_id varchar_pattern_ops);


--
-- Name: servicio_tipo_servicio_id_a92b2abd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX servicio_tipo_servicio_id_a92b2abd ON public.servicio USING btree (tipo_servicio_id);


--
-- Name: tipo_cliente_codigo_0e4eafff_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tipo_cliente_codigo_0e4eafff_like ON public.tipo_cliente USING btree (codigo varchar_pattern_ops);


--
-- Name: trabajador_correo_electronico_004573a2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trabajador_correo_electronico_004573a2_like ON public.trabajador USING btree (correo_electronico varchar_pattern_ops);


--
-- Name: trabajador_cuenta_id_7c90f712; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trabajador_cuenta_id_7c90f712 ON public.trabajador USING btree (cuenta_id);


--
-- Name: trabajador_no_empleado_dcd0315f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trabajador_no_empleado_dcd0315f_like ON public.trabajador USING btree (no_empleado varchar_pattern_ops);


--
-- Name: trabajador_rol_id_f6315938; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trabajador_rol_id_f6315938 ON public.trabajador USING btree (rol_id);


--
-- Name: trabajador_rol_id_f6315938_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trabajador_rol_id_f6315938_like ON public.trabajador USING btree (rol_id varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cuenta cuenta_estado_cuenta_id_da82fe13_fk_estado_cuenta_codigo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_estado_cuenta_id_da82fe13_fk_estado_cuenta_codigo FOREIGN KEY (estado_cuenta_id) REFERENCES public.estado_cuenta(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: datos_cliente datos_cliente_cuenta_id_1a241c4e_fk_cuenta_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datos_cliente
    ADD CONSTRAINT datos_cliente_cuenta_id_1a241c4e_fk_cuenta_id FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: datos_cliente datos_cliente_tipo_cliente_id_b573971f_fk_tipo_cliente_codigo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datos_cliente
    ADD CONSTRAINT datos_cliente_tipo_cliente_id_b573971f_fk_tipo_cliente_codigo FOREIGN KEY (tipo_cliente_id) REFERENCES public.tipo_cliente(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: encuesta encuesta_reservacion_id_9bbd360d_fk_reservacion_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.encuesta
    ADD CONSTRAINT encuesta_reservacion_id_9bbd360d_fk_reservacion_id FOREIGN KEY (reservacion_id) REFERENCES public.reservacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: equipamiento equipamiento_tipo_equipa_id_6021d437_fk_tipo_equipa_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipamiento
    ADD CONSTRAINT equipamiento_tipo_equipa_id_6021d437_fk_tipo_equipa_id FOREIGN KEY (tipo_equipa_id) REFERENCES public.tipo_equipa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_equipa inventario_equipa_equipamiento_id_919efa50_fk_equipamiento_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_equipa
    ADD CONSTRAINT inventario_equipa_equipamiento_id_919efa50_fk_equipamiento_id FOREIGN KEY (equipamiento_id) REFERENCES public.equipamiento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_equipa inventario_equipa_estado_equipa_id_08c3eee0_fk_estado_eq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_equipa
    ADD CONSTRAINT inventario_equipa_estado_equipa_id_08c3eee0_fk_estado_eq FOREIGN KEY (estado_equipa_id) REFERENCES public.estado_equipa(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_mobil inventario_mobil_estado_mobil_id_63c376f7_fk_estado_mo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_mobil
    ADD CONSTRAINT inventario_mobil_estado_mobil_id_63c376f7_fk_estado_mo FOREIGN KEY (estado_mobil_id) REFERENCES public.estado_mobil(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_mobil inventario_mobil_mobiliario_id_bdd44c7b_fk_mobiliario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventario_mobil
    ADD CONSTRAINT inventario_mobil_mobiliario_id_bdd44c7b_fk_mobiliario_id FOREIGN KEY (mobiliario_id) REFERENCES public.mobiliario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mobiliario_descripcion_mob mobiliario_descripci_caractermobil_id_2dbdf09e_fk_caracter_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobiliario_descripcion_mob
    ADD CONSTRAINT mobiliario_descripci_caractermobil_id_2dbdf09e_fk_caracter_ FOREIGN KEY (caractermobil_id) REFERENCES public.caracter_mobi(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mobiliario_descripcion_mob mobiliario_descripci_mobiliario_id_4edf83ce_fk_mobiliari; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobiliario_descripcion_mob
    ADD CONSTRAINT mobiliario_descripci_mobiliario_id_4edf83ce_fk_mobiliari FOREIGN KEY (mobiliario_id) REFERENCES public.mobiliario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mobiliario mobiliario_tipo_movil_id_56c345c4_fk_tipo_mobil_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobiliario
    ADD CONSTRAINT mobiliario_tipo_movil_id_56c345c4_fk_tipo_mobil_id FOREIGN KEY (tipo_movil_id) REFERENCES public.tipo_mobil(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: montaje_mobilairio montaje_mobilairio_mobiliario_id_c96f85b8_fk_mobiliario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.montaje_mobilairio
    ADD CONSTRAINT montaje_mobilairio_mobiliario_id_c96f85b8_fk_mobiliario_id FOREIGN KEY (mobiliario_id) REFERENCES public.mobiliario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: montaje_mobilairio montaje_mobilairio_montaje_id_01d9cb23_fk_montaje_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.montaje_mobilairio
    ADD CONSTRAINT montaje_mobilairio_montaje_id_01d9cb23_fk_montaje_id FOREIGN KEY (montaje_id) REFERENCES public.montaje(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: montaje montaje_salon_id_b5f87ced_fk_salon_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.montaje
    ADD CONSTRAINT montaje_salon_id_b5f87ced_fk_salon_id FOREIGN KEY (salon_id) REFERENCES public.salon(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: montaje montaje_tipo_montaje_id_9d5bfdc9_fk_tipo_montaje_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.montaje
    ADD CONSTRAINT montaje_tipo_montaje_id_9d5bfdc9_fk_tipo_montaje_id FOREIGN KEY (tipo_montaje_id) REFERENCES public.tipo_montaje(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pago pago_concepto_pago_id_fd93a518_fk_concepto_pago_codigo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT pago_concepto_pago_id_fd93a518_fk_concepto_pago_codigo FOREIGN KEY (concepto_pago_id) REFERENCES public.concepto_pago(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pago pago_metodo_pago_id_a0b7dc7c_fk_metodo_pago_codigo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT pago_metodo_pago_id_a0b7dc7c_fk_metodo_pago_codigo FOREIGN KEY (metodo_pago_id) REFERENCES public.metodo_pago(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pago pago_reservacion_id_26479676_fk_reservacion_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT pago_reservacion_id_26479676_fk_reservacion_id FOREIGN KEY (reservacion_id) REFERENCES public.reservacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: registr_esta_reserva registr_esta_reserva_estado_reserva_id_644e722d_fk_estado_re; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registr_esta_reserva
    ADD CONSTRAINT registr_esta_reserva_estado_reserva_id_644e722d_fk_estado_re FOREIGN KEY (estado_reserva_id) REFERENCES public.estado_reserva(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: registr_esta_reserva registr_esta_reserva_reservacion_id_5fc3eef8_fk_reservacion_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registr_esta_reserva
    ADD CONSTRAINT registr_esta_reserva_reservacion_id_5fc3eef8_fk_reservacion_id FOREIGN KEY (reservacion_id) REFERENCES public.reservacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: registr_esta_salon registr_esta_salon_estado_salon_id_548a8918_fk_estado_sa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registr_esta_salon
    ADD CONSTRAINT registr_esta_salon_estado_salon_id_548a8918_fk_estado_sa FOREIGN KEY (estado_salon_id) REFERENCES public.estado_salon(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: registr_esta_salon registr_esta_salon_salon_id_adbf1493_fk_salon_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registr_esta_salon
    ADD CONSTRAINT registr_esta_salon_salon_id_adbf1493_fk_salon_id FOREIGN KEY (salon_id) REFERENCES public.salon(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reserva_equipa reserva_equipa_equipamiento_id_26d8d847_fk_equipamiento_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva_equipa
    ADD CONSTRAINT reserva_equipa_equipamiento_id_26d8d847_fk_equipamiento_id FOREIGN KEY (equipamiento_id) REFERENCES public.equipamiento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reserva_equipa reserva_equipa_reservacion_id_0b171f76_fk_reservacion_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva_equipa
    ADD CONSTRAINT reserva_equipa_reservacion_id_0b171f76_fk_reservacion_id FOREIGN KEY (reservacion_id) REFERENCES public.reservacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservacion reservacion_cliente_id_88926292_fk_datos_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion
    ADD CONSTRAINT reservacion_cliente_id_88926292_fk_datos_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.datos_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservacion reservacion_estado_reserva_id_8cb72091_fk_estado_reserva_codigo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion
    ADD CONSTRAINT reservacion_estado_reserva_id_8cb72091_fk_estado_reserva_codigo FOREIGN KEY (estado_reserva_id) REFERENCES public.estado_reserva(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservacion reservacion_montaje_id_f3642367_fk_montaje_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion
    ADD CONSTRAINT reservacion_montaje_id_f3642367_fk_montaje_id FOREIGN KEY (montaje_id) REFERENCES public.montaje(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservacion_reserva_servicio reservacion_reserva__reservacion_id_40dd2fd0_fk_reservaci; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion_reserva_servicio
    ADD CONSTRAINT reservacion_reserva__reservacion_id_40dd2fd0_fk_reservaci FOREIGN KEY (reservacion_id) REFERENCES public.reservacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservacion_reserva_servicio reservacion_reserva__servicio_id_cf6d223a_fk_servicio_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion_reserva_servicio
    ADD CONSTRAINT reservacion_reserva__servicio_id_cf6d223a_fk_servicio_ FOREIGN KEY (servicio_id) REFERENCES public.servicio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservacion reservacion_tipo_evento_id_fa708b83_fk_tipo_evento_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion
    ADD CONSTRAINT reservacion_tipo_evento_id_fa708b83_fk_tipo_evento_id FOREIGN KEY (tipo_evento_id) REFERENCES public.tipo_evento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservacion_traba_reserva reservacion_traba_re_reservacion_id_646b0526_fk_reservaci; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion_traba_reserva
    ADD CONSTRAINT reservacion_traba_re_reservacion_id_646b0526_fk_reservaci FOREIGN KEY (reservacion_id) REFERENCES public.reservacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservacion_traba_reserva reservacion_traba_re_trabajador_id_8a428469_fk_trabajado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservacion_traba_reserva
    ADD CONSTRAINT reservacion_traba_re_trabajador_id_8a428469_fk_trabajado FOREIGN KEY (trabajador_id) REFERENCES public.trabajador(no_empleado) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: salon salon_estado_salon_id_f03c9bd4_fk_estado_salon_codigo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.salon
    ADD CONSTRAINT salon_estado_salon_id_f03c9bd4_fk_estado_salon_codigo FOREIGN KEY (estado_salon_id) REFERENCES public.estado_salon(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: servicio servicio_tipo_servicio_id_a92b2abd_fk_tipo_servicio_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.servicio
    ADD CONSTRAINT servicio_tipo_servicio_id_a92b2abd_fk_tipo_servicio_id FOREIGN KEY (tipo_servicio_id) REFERENCES public.tipo_servicio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trabajador trabajador_cuenta_id_7c90f712_fk_cuenta_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trabajador
    ADD CONSTRAINT trabajador_cuenta_id_7c90f712_fk_cuenta_id FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trabajador trabajador_rol_id_f6315938_fk_rol_codigo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trabajador
    ADD CONSTRAINT trabajador_rol_id_f6315938_fk_rol_codigo FOREIGN KEY (rol_id) REFERENCES public.rol(codigo) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict qe1fm8QQfR2nt0aYEwXMy0DhEqrtaysikfL9tm8Ibeg3RYSvqoVXIyCgcFbOVdP

