from django.urls import path
from . import views

urlpatterns = [
    path('', views.login, name="login"),
    path('sign_up/', views.sign_up, name="sign_up"),
    path('home/', views.home, name="home"),
    path('reservacion/<int:pk>/json/', views.reservacion_detalle_json, name='reservacion_detalle_json'),
    path('reservacion/', views.reservacion, name="reservacion"),
    path('administracion/servicios/', views.servicios, name="servicios"),
    path('recepcion/historial/', views.historial_reservacion, name="historial_reservacion"),
    path('almacen/inventario-equipamiento/', views.inventario_equipamiento, name="inventario_equipamiento"),
    path('almacen/inventario-mobiliario/', views.inventario_mobiliario, name="inventario_mobiliario"),
    path('recepcion/pagos/', views.pagos, name="pagos"),
    path('administracion/estadisticas/', views.estadisticas, name="estadisticas"),
    path('administracion/trabajadores/', views.trabajadores, name="trabajadores"),
    path('administracion/trabajadores/registrar/', views.registrar_trabajador, name="registrar_trabajador"),
    path('administracion/salones/', views.salones, name="salones"),
    path('administracion/mobiliario/', views.mobiliario, name="mobiliario"),
    path('administracion/equipamiento/', views.equipamiento, name="equipamiento"),
    path('almacen/inventario-equipamiento/actualizar/',views.actualizar_estado_equipamiento, name="actualizar_estado_equipamiento"),
    path("almacen/inventario-mobiliario/", views.inventario_mobiliario, name="inventario_mobiliario"),
    path("almacen/actualizar-estado-mobiliario/", views.actualizar_estado_mobiliario, name="actualizar_estado_mobiliario"),
    path('almacen/resumen-estados/<int:inventario_id>/', views.obtener_resumen_estados, name='resumen_estados'),
    path('almacen/resumen-estados-mob/<int:inventario_id>/', views.obtener_resumen_estados_mob, name='resumen_estados_mob'),
    path('api/inventario/mobiliario/lista/', views.api_lista_mobiliario, name='api_lista_mobiliario'),
    path('api/inventario/mobiliario/mover/', views.api_mover_mobiliario, name='api_mover_mobiliario'),
    path('api/inventario/equipamiento/lista/', views.api_lista_equipamiento, name='api_lista_equipamiento'),
    path('api/inventario/equipamiento/mover/', views.api_mover_equipamiento, name='api_mover_equipamiento'),
    path('api/estados/mobiliario/', views.api_estados_mobiliario, name='api_estados_mobiliario'),
    path('api/estados/equipamiento/', views.api_estados_equipamiento, name='api_estados_equipamiento'),
]
