from django.urls import path
from . import views

urlpatterns = [
    path('', views.login, name="login"),
    path('sign_up/', views.sign_up, name="sign_up"),
    path('home/', views.Home.as_view(), name="home"),
    path('reservacion/', views.ReservacionView.as_view(), name="reservacion"),
    path('home/<int:pk>/json/', views.reservacion_detalle_json, name='reservacion_detalle_json'),
    path('reservacion/buscar-cliente/', views.buscar_cliente, name='buscar_cliente'),
    path('reservacion/servicios-por-tipo/', views.obtener_servicios_por_tipo, name='obtener_servicios_por_tipo'),
    path('reservacion/equipamiento-por-tipo/', views.obtener_equipamiento_por_tipo, name='obtener_equipamiento_por_tipo'),
    path('reservacion/<int:pk>/', views.DetallesReservacionView.as_view(), name="reservacion"),
    path('administracion/servicios/', views.Servicios.as_view(), name="servicios"),
    path('administracion/servicios/<int:pk>/actualizar/', views.actualizar_servicio, name="actualizar_servicio"),
    # path('recepcion/historial/', views.historial_reservacion, name="historial_reservacion"),
    path('recepcion/historial/', views.HistorialReservacionViw.as_view(), name="historial_reservacion"),
    path('recepcion/historial/<int:pk>/json/', views.historial_detalle, name="historial_detalle_json"),
    path('recepcion/historial/<int:pk>/actualizar/', views.actualizar_reservacion, name="actualizar_reservacion"),
    path('almacen/inventario-equipamiento/', views.inventario_equipamiento, name="inventario_equipamiento"),
    path('almacen/inventario-mobiliario/', views.inventario_mobiliario, name="inventario_mobiliario"),
    path('recepcion/pagos/', views.pagos, name="pagos"),
    path('administracion/estadisticas/', views.estadisticas, name="estadisticas"),
    path('administracion/trabajadores/', views.Trabajadores.as_view(), name="trabajadores"),
    path('administracion/trabajadores/registrar/', views.registrar_trabajador, name="registrar_trabajador"),
    path('administracion/salones/', views.Salones.as_view(), name="salones"),
    path('administracion/salones/<int:pk>/actualizar/', views.actualizar_salon, name="actualizar_salon"),
    path('administracion/mobiliario/', views.Mobiliarios.as_view(), name="mobiliario"),
    path('administracion/mobiliario/<int:pk>/actualizar/', views.actualizar_mobiliario, name="actualizar_mobiliario"),
    path('administracion/equipamiento/', views.Equipamientos.as_view(), name="equipamiento"),
    path('administracion/equipamiento/<int:pk>/actualizar/', views.actualizar_equipamiento, name="actualizar_equipamiento"),
    path('administracion/trabajadores/<str:pk>/actualizar/', views.actualizar_trabajador, name="actualizar_trabajador"),
]
