# Generated by Django 6.0.3 on 2026-03-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('disposicion', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'db_table': 'tipo_servicio',
            },
        ),
    ]
