# Generated by Django 6.0.3 on 2026-03-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoomApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de cuenta',
                'db_table': 'estado_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rol',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de cliente',
                'db_table': 'tipo_cliente',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('disposicion', models.BooleanField(default=True)),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookingRoomApp.estadocuenta')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'db_table': 'cuenta',
            },
        ),
        migrations.CreateModel(
            name='DatosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('nombre_fiscal', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidoPaterno', models.CharField(max_length=150)),
                ('apelidoMaterno', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('dir_colonia', models.CharField(max_length=150)),
                ('dir_calle', models.CharField(max_length=150)),
                ('dir_numero', models.CharField(max_length=50)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookingRoomApp.cuenta')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookingRoomApp.tipocliente')),
            ],
            options={
                'verbose_name': 'Datos del cliente',
                'db_table': 'datos_cliente',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('no_empleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rfc', models.CharField(max_length=13)),
                ('nombre_fiscal', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidoPaterno', models.CharField(max_length=150)),
                ('apelidoMaterno', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookingRoomApp.cuenta')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookingRoomApp.rol')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'db_table': 'trabajador',
            },
        ),
    ]
