# Generated by Django 6.0.3 on 2026-03-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoomApp', '0002_estadocuenta_rol_tipocliente_cuenta_datoscliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocliente',
            name='disposicion',
            field=models.BooleanField(default=True),
        ),
    ]
