# Generated by Django 6.0.3 on 2026-03-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoomApp', '0003_tipocliente_disposicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='datoscliente',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
