# Generated by Django 6.0.3 on 2026-03-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoomApp', '0004_cuenta_firebase_uid_alter_cuenta_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
