# Generated by Django 6.0.3 on 2026-03-24 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRoomApp', '0005_alter_rol_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracterMobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Característica de mobiliario',
                'db_table': 'caracter_mobi',
            },
        ),
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Concepto de pago',
                'db_table': 'concepto_pago',
            },
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('descripcion', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'db_table': 'equipamiento',
            },
        ),
        migrations.CreateModel(
            name='EstadoEquipa',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de equipamiento',
                'db_table': 'estado_equipa',
            },
        ),
        migrations.CreateModel(
            name='EstadoMobil',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de mobiliario',
                'db_table': 'estado_mobil',
            },
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de reserva',
                'db_table': 'estado_reserva',
            },
        ),
        migrations.CreateModel(
            name='EstadoSalon',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de salón',
                'db_table': 'estado_salon',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Método de pago',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Montaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Montaje',
                'db_table': 'montaje',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('disposicion', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de equipamiento',
                'db_table': 'tipo_equipa',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('disposicion', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de evento',
                'db_table': 'tipo_evento',
            },
        ),
        migrations.CreateModel(
            name='TipoMobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('disposicion', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de mobiliario',
                'db_table': 'tipo_mobil',
            },
        ),
        migrations.CreateModel(
            name='TipoMontaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('disposicion', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de montaje',
                'db_table': 'tipo_montaje',
            },
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('descripcion', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('descripcion_mob', models.ManyToManyField(to='BookingRoomApp.caractermobil')),
                ('tipo_movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.tipomobil')),
            ],
            options={
                'verbose_name': 'Mobiliario',
                'db_table': 'mobiliario',
            },
        ),
        migrations.CreateModel(
            name='MontajeMobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('mobiliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.mobiliario')),
                ('montaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.montaje')),
            ],
            options={
                'verbose_name': 'Mobiliarios de un Montaje',
                'db_table': 'montaje_mobilairio',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripEvento', models.CharField(max_length=50)),
                ('estimaAsistentes', models.IntegerField()),
                ('fechaReservacion', models.DateField(auto_now_add=True)),
                ('fechaEvento', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.datoscliente')),
                ('estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.estadoreserva')),
                ('montaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.montaje')),
                ('traba_reserva', models.ManyToManyField(to='BookingRoomApp.trabajador')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'db_table': 'reservacion',
            },
        ),
        migrations.CreateModel(
            name='RegistrEstadReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.estadoreserva')),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.reservacion')),
            ],
            options={
                'verbose_name': 'Registro de estados de Reservacion',
                'db_table': 'registr_esta_reserva',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('no_pago', models.IntegerField()),
                ('concepto_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.conceptopago')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.metodopago')),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.reservacion')),
            ],
            options={
                'verbose_name': 'Pago',
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.IntegerField()),
                ('equipamiento', models.IntegerField()),
                ('servicios', models.IntegerField()),
                ('salon', models.IntegerField()),
                ('mobiliario', models.IntegerField()),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.reservacion')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='ReservaEquipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('equipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.equipamiento')),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.reservacion')),
            ],
            options={
                'verbose_name': 'Equipamientos de Reserva',
                'db_table': 'reserva_equipa',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion', models.CharField(max_length=100)),
                ('dimenLargo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimenAncho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimenAlto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metrosCuadrados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxCapacidad', models.IntegerField()),
                ('estado_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.estadosalon')),
            ],
            options={
                'verbose_name': 'Salon',
                'db_table': 'salon',
            },
        ),
        migrations.CreateModel(
            name='RegistrEstadSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('estado_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.estadosalon')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.salon')),
            ],
            options={
                'verbose_name': 'Registro de estados de Salon',
                'db_table': 'registr_esta_salon',
            },
        ),
        migrations.AddField(
            model_name='montaje',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.salon'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('descripcion', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disposicion', models.BooleanField()),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.tiposervicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'db_table': 'servicio',
            },
        ),
        migrations.AddField(
            model_name='reservacion',
            name='reserva_servicio',
            field=models.ManyToManyField(to='BookingRoomApp.servicio'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='tipo_equipa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.tipoequipa'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.tipoevento'),
        ),
        migrations.AddField(
            model_name='montaje',
            name='tipo_montaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.tipomontaje'),
        ),
        migrations.CreateModel(
            name='InventarioEquipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('equipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.equipamiento')),
                ('estado_equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.estadoequipa')),
            ],
            options={
                'verbose_name': 'Estado de Equipamientos',
                'db_table': 'inventario_equipa',
                'constraints': [models.UniqueConstraint(fields=('equipamiento', 'estado_equipa'), name='estado_equipamiento')],
            },
        ),
        migrations.CreateModel(
            name='InventarioMob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('estado_mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.estadomobil')),
                ('mobiliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingRoomApp.mobiliario')),
            ],
            options={
                'verbose_name': 'Estado de Mobilarios',
                'db_table': 'inventario_mobil',
                'constraints': [models.UniqueConstraint(fields=('mobiliario', 'estado_mobil'), name='estado_mobiliario')],
            },
        ),
    ]
